name: Build and Test for Coolify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Build application
      run: npm run build
      env:
        # Provide placeholder values for build testing
        NEXT_PUBLIC_SUPABASE_URL: https://placeholder.supabase.co
        NEXT_PUBLIC_SUPABASE_ANON_KEY: placeholder-anon-key
        SUPABASE_SERVICE_ROLE_KEY: placeholder-service-key
        ADMIN_USERNAME: test-admin
        ADMIN_PASSWORD: test-password-for-build
        JWT_SECRET: test-jwt-secret-key-minimum-32-characters-long
        NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY: pk_test_placeholder
        PAYSTACK_SECRET_KEY: sk_test_placeholder
        ZOHO_EMAIL_USER: test@example.com
        ZOHO_EMAIL_PASSWORD: placeholder-password
        NEXT_PUBLIC_SITE_URL: http://localhost:3000

    - name: Check build output
      run: |
        if [ -d ".next" ]; then
          echo "✅ Build successful - .next directory created"
          ls -la .next/
        else
          echo "❌ Build failed - no .next directory"
          exit 1
        fi

  # This job only runs on the main branch to avoid unnecessary notifications
  notify-coolify:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Notify successful build
      run: |
        echo "✅ Build successful on main branch"
        echo "🚀 Coolify should automatically deploy this commit"
        echo "📋 Commit: ${{ github.sha }}"
        echo "👤 Author: ${{ github.actor }}"